Squashed commit of the following:
commit f6bdd5431c768e0d7767112970419838bdd65b83
Author: Jeff Whiting <Jeff.Whiting@noaa.gov>
Date:   Wed Aug 29 23:17:51 2018 +0000

    Vlab Issue #48364 - final version of Release_Notes.txt

    Change-Id: Icd0a77eddcac94bfcf6eb5298ddde5328b74a91a

commit 8c753a7e2d828061a9620a86b0a467cf2094f8c7
Author: Jeff Whiting <Jeff.Whiting@noaa.gov>
Date:   Wed Aug 29 22:54:11 2018 +0000

    Vlab Issue #48364 final update to ush/dumpjb

    Change-Id: I2eae5e436a9b6e9c189e7013d399dbfe2e879a2b

commit 089c0937d0c3d1d692464b58683089a870d93440
Author: Jeff Whiting <Jeff.Whiting@noaa.gov>
Date:   Wed Aug 29 21:22:20 2018 +0000

    Vlab Issue #48364 : ush/dumpjb cleanup; Release_Notes.txt edit

    Change-Id: I1b5bcc70ac222d44ffc562ff05951dbb33f36626

commit cfb97aeea3d15f77233361099710ed6c4d00b089
Author: Jeff Whiting <Jeff.Whiting@noaa.gov>
Date:   Wed Aug 29 17:19:46 2018 +0000

    Vlab Issue #48364 removed modulefile 4.1.0

    Change-Id: Idc90f1572a6d9e3470b83448dc93dabe620e082e

commit a8535d59f3178ae822971ec279f765d01ef5e4f5
Author: Jeff Whiting <Jeff.Whiting@noaa.gov>
Date:   Wed Aug 29 17:18:20 2018 +0000

    Vlab Issue #48364 : modulefile 5.0.0 creation

    Change-Id: I7ff376c4019e53665b85f80a8657be33abf0411b

commit 4f96e47898ef3b3abe7e80fef56359ea3e565331
Author: Jeff.Whiting <Jeff.Whiting@noaa.gov>
Date:   Thu Jul 26 21:10:54 2018 +0000

    Vlab Issue #48364 - branch obsproc_dump.iss48364.ph3_port
    Bug fix of ush/dumpjb script w/ TMPDIR settings for Dells
    Release_Notes.txt draft edits
    Testing w/ latest libs for p2 & cray

    Change-Id: Id820b9071a572731d388f5022498fe61f730e83a

commit cde326bf059c7a0b0c0b2cdd8772691516c181b7
Author: Jeff.Whiting <Jeff.Whiting@noaa.gov>
Date:   Thu Jul 26 19:08:55 2018 +0000

    Vlab Issue #48364 - branch obsproc_dump.iss48364.ph3_port
    Update of sorc/build.sh script; Release_Notes.txt draft update

    Change-Id: I1492b5b57cbc5f3fe29301f75ce75a4188408b1d

commit 3255666b1b6f63b8d820e98442b10416994de8a5
Author: Jeff.Whiting <Jeff.Whiting@noaa.gov>
Date:   Thu Jul 26 17:07:48 2018 +0000

    Vlab Issue #48364 - branch obsproc_dump.iss48364.ph3_port
    Update of ush/dumpjb script w/ TMPDIR settings for Dells

    Change-Id: Ie82c2f840dcb3fa3e147d1dd197dcf7369c58ac1

commit efc31e817394fe5e017e285b632240529a75c921
Author: Jeff.Whiting <Jeff.Whiting@noaa.gov>
Date:   Thu Jul 19 21:41:35 2018 +0000

    Vlab Issue #48364 - branch obsproc_dump.iss48364.ph3_port
    Update of build.sh script; Added of new clobber.sh script.

    Change-Id: I24b2472103988c892a3b43cb0c73ff7dfffae323

commit d908d83220c81b0ca035a4c64ba6b87fb6b6369a
Merge: 91cadc7 100c680
Author: Jeff.Whiting <Jeff.Whiting@noaa.gov>
Date:   Tue May 15 19:56:36 2018 +0000

    Merge branch 'master' into obsproc_dump.iss48364.ph3_port

commit 91cadc7726e876c11fcfc57c148cb611743827b3
Author: Jeff.Whiting <Jeff.Whiting@noaa.gov>
Date:   Thu May 10 18:49:32 2018 +0000

    Vlab Issue #48364 - dumpjb works for lmp & glmp

    Working version of dumpjb - reproduces lmp & glmp jobs
    Still contains debug content.
    Does not include explicit module versions.

commit 8489586de1da8d99e78e903cbe4765f2cc73845e
Author: Jeff.Whiting <Jeff.Whiting@noaa.gov>
Date:   Fri Apr 27 19:59:50 2018 +0000

    Vlab Issue #48364 - branch obsproc_dump.iss48364.ph3_port

    Update of build.sh script.

commit 13bf15ee4699055624c8c32dd94eb0b53feeee4f
Author: Jeff.Whiting <Jeff.Whiting@noaa.gov>
Date:   Tue Apr 24 19:22:58 2018 +0000

    [src]:EMC_obsproc_dump (branch:obsproc_dump.iss48364.ph3_port)

    Intermediate commit of DB changes.

Change-Id: I5b86112e10cc19cb19b3740eeeefcd593878dbbf

diff --git a/ush/dumpjb b/ush/dumpjb
--- a/ush/dumpjb
+++ b/ush/dumpjb
@@ -212,7 +212,7 @@
 #     BUFR_DUMPMD must still be run for all types because it will write the
 #     dummy messages to the dump file since BUFR_COMBFR does not run in this
 #     case); added new script variable DUMPMD which controls the execution of
-#     BUFR_DUMPMD {there may be cases where BUFR_DUMPMD need not run in order
+#     BUFR_DUMPMD (there may be cases where BUFR_DUMPMD need not run in order
 #     to save computation time (e.g., Level 2 radial wind or reflectivity types
 #     in 1-hour tanks) - before BUFR_DUMPMD always ran in every thread), see
 #     comments about script variable DUMPMD in remarks section below; checks to
@@ -330,7 +330,13 @@
 #       filesystem rather than /gpfs/hps.
 # 2018-05-04  Y. Ling  Added VIIRS SST mesgtyp/subtyp 012/023, 012/024 012/025 for 
 #       setting the DUPE1 and DUPE2 parameters.
+# 2018-08-29  JWhiting  Updated to run on Dell-p3 platforms: 
+#     - added logic to detect Dell-p3 system and initialize Modules;
+#     - disabled exact matching of Dell-p3 module versions (LMOD_EXACT_MATCH=no);
+#     - added default value for TMPDIR on Dell-p3 systems;
+#     - added checks for Dell-p3 user temporary directory filesystems.
 #
+###
 #
 # Usage: dumpjb  yyyymmddhh<.hh> hh<.hh> dgrp1 dgrp2 dgrp3 ... dgrpN
 #
@@ -930,7 +936,7 @@ echo
 echo "********************************************************************"
 echo "********************************************************************"
 echo "     STARTING EXECUTION OF THE UNIVERSAL DUMP SCRIPT - DUMPJB       "
-echo "                            08-30-2017                              "
+echo "                            08-29-2018                              "
 echo "             Start time: `date -u`                                  "
 echo "********************************************************************"
 echo "********************************************************************"
@@ -941,10 +947,26 @@ RETG=0
 
 # Initialize the Modules package in case we need to load an environmment module
 #  (update the following lines if this script moves away from ksh)
-if [ -f /usrx/local/Modules/default/init/ksh ]; then
+# -- assumes module init files are unique to each system;
+if [ -f /usrx/local/Modules/default/init/ksh ]; then          # IBM-p1/2
     . /usrx/local/Modules/default/init/ksh > /dev/null
-elif [ -f /opt/modules/default/init/ksh ]; then
+
+elif [ -f /opt/modules/default/init/ksh ]; then               # Cray-XC40
     . /opt/modules/default/init/ksh  > /dev/null
+
+elif [ -f /usrx/local/prod/lmod/lmod/init/profile ] ; then    # Dell-p3 
+    . /usrx/local/prod/lmod/lmod/init/profile > /dev/null
+    . /usrx/local/prod/modulefiles/.defaultmodules > /dev/null
+
+    LMOD_EXACT_MATCH=no
+
+else
+  echo "ERROR: could not initialize module environment"
+  echo
+  echo "ABNORMAL EXIT!!!!!!!!!!!"
+  echo
+  [ $LOUD = on ] && set -x
+  exit 99
 fi
 [ -z "$sys_tp" ] && sys_tp=$(module load prod_util 2>/dev/null;getsystem.pl -tp)
 
@@ -1064,6 +1086,7 @@ else # put DATA_DUMPJB under $TMPDIR
        Cray-XC40) TMPDIR=/gpfs/hps3/stmp/$USER;;
           IBM-p1) TMPDIR=/stmpd1/$USER;;
           IBM-p2) TMPDIR=/stmpd3/$USER;;
+         Dell-p3) TMPDIR=/gpfs/dell2/stmp/$USER;;
         *) 
       set +x
       echo "*******************************************************************"
@@ -1099,7 +1122,9 @@ else # put DATA_DUMPJB under $TMPDIR
 #  This will help to minimize the number of subdirectories directly under 
 #  the root scrub dir.
     case ${TMPDIR%\/} in     # a trailing slash is ignored
-      /stmp | /stmp?? | /ptmp | /ptmp?? | /gpfs/???/[sp]tmp | /gpfs/????/[sp]tmp )
+      /stmp | /stmp?? | /ptmp | /ptmp?? | \
+      /gpfs/???/[sp]tmp | /gpfs/????/[sp]tmp | \
+      /gfps/dell?/[sp]tmp )
           [ -n "$USER" ] && TMPDIR=${TMPDIR%\/}/$USER;;
     esac
   fi
